export const roomsItem = [
   {
      id: "1",
      title: "Apartment in Dhaka",
      picture: "https://picsum.photos/350/300?random=1",
      price: 59,
      nights: 2,
      avgRating: 4.9,
   },
   {
      id: "2",
      title: "Room in Roncesvalles",
      picture: "https://picsum.photos/350/300?random=2",
      price: 72,
      nights: 3,
      avgRating: 4.7,
   },
   {
      id: "3",
      title: "Entire rental unit in Seoul",
      picture: "https://picsum.photos/350/300?random=3",
      price: 88,
      nights: 2,
      avgRating: 4.8,
   },
   {
      id: "4",
      title: "Beachfront villa in Bali",
      picture: "https://picsum.photos/350/300?random=4",
      price: 210,
      nights: 4,
      avgRating: 5.0,
   },
   {
      id: "5",
      title: "Mountain cabin in Colorado",
      picture: "https://picsum.photos/350/300?random=5",
      price: 150,
      nights: 5,
      avgRating: 4.6,
   },
   {
      id: "6",
      title: "Studio in Paris",
      picture: "https://picsum.photos/350/300?random=6",
      price: 130,
      nights: 2,
      avgRating: 4.8,
   },
   {
      id: "7",
      title: "Loft in New York",
      picture: "https://picsum.photos/350/300?random=7",
      price: 240,
      nights: 3,
      avgRating: 4.9,
   },
   {
      id: "8",
      title: "Traditional Ryokan in Kyoto",
      picture: "https://picsum.photos/350/300?random=8",
      price: 110,
      nights: 2,
      avgRating: 4.7,
   },
   {
      id: "9",
      title: "Countryside cottage in England",
      picture: "https://picsum.photos/350/300?random=9",
      price: 95,
      nights: 4,
      avgRating: 4.8,
   },
   {
      id: "10",
      title: "Lake house in Finland",
      picture: "https://picsum.photos/350/300?random=10",
      price: 175,
      nights: 3,
      avgRating: 4.9,
   },
   {
      id: "11",
      title: "Desert camp in Morocco",
      picture: "https://picsum.photos/350/300?random=11",
      price: 70,
      nights: 2,
      avgRating: 4.6,
   },
   {
      id: "12",
      title: "Penthouse in Dubai",
      picture: "https://picsum.photos/350/300?random=12",
      price: 320,
      nights: 2,
      avgRating: 5.0,
   },
   {
      id: "13",
      title: "Treehouse in Costa Rica",
      picture: "https://picsum.photos/350/300?random=13",
      price: 90,
      nights: 3,
      avgRating: 4.7,
   },
   {
      id: "14",
      title: "Historic home in Rome",
      picture: "https://picsum.photos/350/300?random=14",
      price: 140,
      nights: 2,
      avgRating: 4.8,
   },
   {
      id: "15",
      title: "Houseboat in Amsterdam",
      picture: "https://picsum.photos/350/300?random=15",
      price: 120,
      nights: 3,
      avgRating: 4.9,
   },
   {
      id: "16",
      title: "Eco lodge in the Amazon",
      picture: "https://picsum.photos/350/300?random=16",
      price: 85,
      nights: 4,
      avgRating: 4.6,
   },
   {
      id: "17",
      title: "Chalet in the Swiss Alps",
      picture: "https://picsum.photos/350/300?random=17",
      price: 200,
      nights: 5,
      avgRating: 4.9,
   },
   {
      id: "18",
      title: "Bungalow in the Maldives",
      picture: "https://picsum.photos/350/300?random=18",
      price: 260,
      nights: 3,
      avgRating: 5.0,
   },
   {
      id: "19",
      title: "Riad in Marrakech",
      picture: "https://picsum.photos/350/300?random=19",
      price: 100,
      nights: 2,
      avgRating: 4.7,
   },
   {
      id: "20",
      title: "Farm stay in Tuscany",
      picture: "https://picsum.photos/350/300?random=20",
      price: 115,
      nights: 4,
      avgRating: 4.8,
   },
];
